# 
- hosts: [aws]
  sudo: yes
#  gether_facts: no

  tasks:
# Basic provisioning example
#  - ec2:
#    key_name: 
#    instance_type: t2.small
#    image: ami-123456
#    wait: yes
#    group: webserver
#    count: 3
#    vpc_subnet_id: subnet-29e63245
#    assign_public_ip: yes
#
  - name: Apt update
    apt: update_cache=yes

  - name: Install packages
    apt: name= {{ item }} state=present
    with_items:
      - pip
      - git
      - maven

  - name: Install gevent package
    pip: name=gevent state=present
